### ISSUE TITLE
Not creating the WHAM mixture

### ISSUE THREAD

**Issue by ntyoshi** [mpariente/asteroid#153] opened 2020-06-14 17:57 UTC
When I tried to ConvTasnet with WHAM ([link](https://github.com/mpariente/asteroid/tree/master/egs/wham/ConvTasNet)) from stage 0,
I got a problem at stage 1 ‘Run python scripts to create the WHAM mixtures’.

The echoed log was below

```
Run python scripts to create the WHAM mixtures
16k max dataset, tr split
Completed 500 of 20000 utterances
Completed 1000 of 20000 utterances
Completed 1500 of 20000 utterances
Completed 2000 of 20000 utterances
Completed 2500 of 20000 utterances
Completed 3000 of 20000 utterances
Traceback (most recent call last):
 File "create_wham_from_scratch.py", line 118, in <module>
   create_wham(args.wsj0_root, args.wham_noise_root, args.output_dir)
 File "create_wham_from_scratch.py", line 93, in create_wham
   s1_samples, s2_samples, noise_samples = append_or_truncate(s1_samples, s2_samples, noise_samples,
 File "/home/ttnt/venv/data/wham/wham_scripts/utils.py", line 47, in append_or_truncate
   s1_append[speech_start_sample:speech_end_sample] = s1_samples
ValueError: could not broadcast input array from shape (145927) into shape (145759)
```

As long as I looked them up, the issue occurred during the 3065th utterance process.
Additionally in utils.py, the **s1_samples** seemed to be too big to put **s1_append[speech_start_sample:speech_end_sample]**.
The length of them were respectively 

- s1_append: 176252
- s1_append[speech_start_sample:speech_end_sample]: 145759
- s1_samples: 145927.

If you have some solutions for this problem or something I should do, please let me know.

My environment is below:
Ubuntu 20.04 on WSL(Windows 10)
Python 3.8.2

Thank you.

**Comment by mpariente** [comment] 2020-06-14 18:55
Hey, thank you for your feedback. 
I never had this problem and we are not the maintainers of the WHAM scripts, we only download them so I'm not sure I can help with this.

I can recommend you to try the LibriMix dataset which is an extension to WHAM (noisy separation as well, with also the 3speaker version), if you have problems on this dataset, I'll be able to help on the generation scripts because we are the maintainers of this script.

**Comment by ntyoshi** [comment] 2020-06-15 04:07
@mpariente 
Thank you for the comment.
I've looked it more then I guess the working memory of my environment is too small.
Because I found the length **s1_append** couldn't become longer than 176252 on my environment.
I am going to find the way to expand the working memory from now on but I would appreciate you if you could check the max length of **s1_append**. It should be longer than 176252.

I'll be here after I try with the environment that has enough memory.

**Comment by mpariente** [comment] 2020-06-15 08:42
```python
        s1_append = np.zeros_like(noise_samples)
        s2_append = np.zeros_like(noise_samples)
        s1_append[speech_start_sample:speech_end_sample] = s1_samples
        s2_append[speech_start_sample:speech_end_sample] = s2_samples
        s1_samples = s1_append
        s2_samples = s2_append
```
If you env memory was too small, you'd get memory error right? I never saw numpy allocating less than requested without throwing an error.

**Comment by ntyoshi** [comment] 2020-06-15 09:06
Oh sorry. I miscoded. Please never mind this part (Because I found the length s1_append couldn't become longer than 176252 on my environment.) of my previous comment.

But at the 3065th utterance process, I printed below.
- speech_start_sample: 30493
- speech_end_sample: 176420
(again)
- len(s1_samples): 145927
- len(s1_append): 176252
- len(s1_append[speech_start_sample:speech_end_sample]): 145759

I suspect **s1_append** should be longer.

**Comment by mpariente** [comment] 2020-06-15 09:09
Can you also give me the value of  `noise_samples` please?

**Comment by ntyoshi** [comment] 2020-06-15 09:14
`len(noise_samples)` is also 176252.

**Comment by mpariente** [comment] 2020-06-15 09:52
Well it seems that the noise file is smaller than the speech files (+ start offset) and this is weird. 
I'd contact the authors of the scripts because at can't help at this point. 

In the mean time, you'll have all the_min_ modes which should work. And that's usually what we use for training so you could generate that while you wait for the _max_ modes to be fixed.

**Comment by ntyoshi** [comment] 2020-06-15 09:57
OK. How should I change the code for all the_min_modes?

This is just curious but you didn't have this issue, right?

**Comment by mpariente** [comment] 2020-06-15 11:35
Yes, it is very curious indeed, I never had this problem. 

```python
            for datalen_dir in ['max', 'min']:
```
Line 49 of create_wham_from_scratch.py

**Comment by mpariente** [comment] 2020-06-22 20:35
How is it going with this?

**Comment by ntyoshi** [comment] 2020-06-22 21:54
What you suggested me last week is working so far.
Thank you.

I'm just waiting for the answer from the authors of the scripts.

**Comment by gwichern** [comment] 2020-06-24 01:17
I am the maintainer of the WHAM! scripts.  Someone alerted me to this issue last night. I ran the script today starting from stage 1 and am unable to reproduce this issue.  However, for the 3065th training utterance in the max case that @ntyoshi mentioned I see `len(s1_samples)=145285` not 145927.  The maximum length speaker for this utterance is _s2_.  @mpariente @ntyoshi what lengths are you seeing for the raw speech files?

```
s1_samples,  sr = sf.read('YOUR_WSJ_ROOT_HERE/wsj0/si_tr_s/20n/20na010o.wav')
s2_samples,  sr = sf.read('YOUR_WSJ_ROOT_HERE/wsj0/si_tr_s/02a/02ac0215.wav')
len(s1_samples)
Output: 79680
len(s2_samples)
Output: 145285
```

**Comment by mpariente** [comment] 2020-06-24 13:36
Thanks Gordon for looking into this ! 
I do have the same output as yours for wavfiles you specified. 
@ntyoshi I guess you'll have the wrong number of samples.. Could you listen if this file sounds ok?

**Comment by ntyoshi** [comment] 2020-06-24 18:10
@gwichern @mpariente 
Thank you for your response.
Please give me time to check them. Sorry for late reply.

**Comment by ntyoshi** [comment] 2020-06-25 08:09
@gwichern 
My result was below:
```
len(s1_samples)
Output: 79680
len(s2_samples)
Output: 145927
```
02ac0215.wav seems to be strange.

@mpariente 
20na010o.wav (4 sec) and 02ac0215.wav (9 sec) are chopped noise.
Are they wired?

**Comment by mpariente** [comment] 2020-06-25 08:54
These should be speech samples, not noise.

**Comment by ntyoshi** [comment] 2020-06-26 10:59
I'm not sure why but when I rerun stage 0, 0na010o.wav and 02ac0215.wav became speech sample.
Then stage 1 went through well!

@mpariente 
Let me ask one thing.
>In the mean time, you'll have all the_min_ modes which should work. And that's usually what we use for training so you could generate that while you wait for the max modes to be fixed.

What do you use max mode for?

**Comment by mpariente** [comment] 2020-06-27 15:59
This is not often used to train current source separation models. 
But for ASR, you'd need both speakers to finish their sentences so you'd need the max mode.

**Comment by mpariente** [comment] 2020-06-27 15:59
As this is solved, I'm closing this

**Closed by mpariente** 2020-06-27 15:59 UTC

**Comment by ntyoshi** [comment] 2020-06-27 17:50
I see. Thank you for everything!
