### ISSUE TITLE
About training DCCRNet

### ISSUE THREAD

**Issue by Tigerwww** [mpariente/asteroid#341] opened 2020-11-20 07:32 UTC
### A fresher wants to train DCCRNet

Hi, sorry to bother you. 

I'm a beginner studying voice conversion, however, I need a denoising model.

I'm planning to train DCCRNet on my own dataset, but I just found no files like run.sh in the DCCRNet recipe. So I need to write it?

And How much time it may take with only one Titan RTX?

Very thanks for answering.

**Comment by jonashaag** [comment] 2020-11-20 11:20
Duplicate of #278. Feel free to continue there if you have more questions!

**Closed by jonashaag** 2020-11-20 11:20 UTC
Labels: question
